name: Update PR Stack
run-name: "${{ github.event.action }} PR #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}"

on:
  pull_request:
    types: [closed, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-pr-stack:
    runs-on: ubuntu-latest
    steps:
      - uses: Phlogistique/autorestack-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
